/**
 * Global site configuration — single source of truth for brand + SEO identity.
 * Used by index.html, schema.org JSON-LD, llms.txt, OG cards and the sitemap plugin.
 */

export const SITE = {
  /** Product name (kept consistent everywhere — brand + domain do NOT match, see notes) */
  name: "ImageForge",
  tagline: "Private Image Compression Studio",
  domain: "imagealchemy.app",
  origin: "https://imagealchemy.app",
  /** Default language / locale — geo targeting signal */
  locale: "en_US",
  language: "en",
  description:
    "Compress, convert and resize images to WebP, AVIF, JPEG and PNG entirely in your browser. Free, private, unlimited batch processing — no uploads, no accounts, no tracking.",
  /** Short pitch used in nav footers + schema descriptions */
  shortDescription:
    "Free, private, browser-based image compression studio. Batch compress to WebP, AVIF, JPEG and PNG with no uploads.",
  themeColor: "#7c3aed",
  themeColorDark: "#0b0a14",
  author: "Alexios Papaioannou",
  /** The genuine source repository */
  repository: "https://github.com/douphealth/form-beauty-studio",
  /** Regions served — free web tool, available worldwide */
  areaServed: "Worldwide",
  /** Supported output formats */
  formats: ["AVIF", "WebP", "JPEG", "PNG"] as const,
  /** Social preview image (self-hosted, generated by scripts/build-og.mjs) */
  ogImage: "/og-image.png",
  ogImageWidth: 1200,
  ogImageHeight: 630,
  /** Twitter handle — left empty until the user provides one */
  twitterHandle: "",
} as const;

export const NAV_GROUPS: { label: string; items: { path: string; label: string }[] }[] = [
  {
    label: "Learn",
    items: [
      { path: "/learn", label: "All guides" },
      { path: "/learn/image-optimization-guide", label: "Image optimization" },
      { path: "/learn/compress-images-for-web", label: "Compress for web" },
      { path: "/learn/webp-vs-avif", label: "WebP vs AVIF" },
      { path: "/learn/core-web-vitals-images", label: "Core Web Vitals" },
      { path: "/learn/best-free-image-compression-tools", label: "Best free tools" },
    ],
  },
  {
    label: "Formats",
    items: [
      { path: "/formats/webp", label: "WebP" },
      { path: "/formats/avif", label: "AVIF" },
      { path: "/formats/jpeg", label: "JPEG" },
      { path: "/formats/png", label: "PNG" },
    ],
  },
  {
    label: "Tools",
    items: [
      { path: "/tools/image-resizer", label: "Image resizer" },
      { path: "/tools/image-converter", label: "Image converter" },
    ],
  },
  {
    label: "Reference",
    items: [
      { path: "/glossary", label: "Glossary" },
      { path: "/about", label: "About" },
      { path: "/privacy", label: "Privacy" },
    ],
  },
];

/** Flat list of every navigable + indexable path (drives the nav + footer). */
export const NAV_PATHS = NAV_GROUPS.flatMap((g) => g.items.map((i) => i.path));
