/**
 * Global site configuration — single source of truth for brand + SEO identity.
 * Used by index.html, schema.org JSON-LD, llms.txt, OG cards and the sitemap plugin.
 */

export const SITE = {
  /** Product name (kept consistent everywhere — brand + domain do NOT match, see notes) */
  name: "ImageAlchemy",
  tagline: "Private Image Compression Studio",
  domain: "imagealchemy.app",
  origin: "https://imagealchemy.app",
  /** Default language / locale — geo targeting signal */
  locale: "en_US",
  language: "en",
  description:
    "Compress, convert and resize images to WebP, AVIF, JPEG and PNG entirely in your browser. Free, private, unlimited batch processing — no uploads, no accounts, no tracking.",
  /** Short pitch used in nav footers + schema descriptions */
  shortDescription:
    "Free, private, browser-based image compression studio. Batch compress to WebP, AVIF, JPEG and PNG with no uploads.",
  themeColor: "#7c3aed",
  themeColorDark: "#0b0a14",
  author: "Alexios Papaioannou",
  /**
   * Source repository.
   *
   * HONESTY NOTE — read before emitting this into JSON-LD `sameAs`.
   *
   * This URL does contain the code that powers this site: pushing to it
   * triggers the production rebuild. But the repository is *named*
   * `form-beauty-studio` and its README is still the stock Lovable template
   * ("Welcome to your Lovable project", `REPLACE_WITH_PROJECT_ID`). A search
   * engine or an AI agent that follows `sameAs` lands on a page that never
   * mentions ImageAlchemy, which weakens rather than strengthens the entity.
   *
   * `repository` is therefore used ONLY where a truthful "the code lives here"
   * pointer is genuinely useful (the About page, for humans). It is deliberately
   * NOT emitted as `sameAs` in the JSON-LD graph — see json-ld.ts. To make the
   * claim strong, push an ImageAlchemy-branded README, then flip
   * `repositoryIsBranded` to true.
   */
  repository: "https://github.com/douphealth/form-beauty-studio",
  repositoryIsBranded: false,
  /** Regions served — free web tool, available worldwide */
  areaServed: "Worldwide",
  /** Supported output formats */
  formats: ["AVIF", "WebP", "JPEG", "PNG"] as const,
  /** Social preview image (self-hosted, generated by scripts/build-og.mjs) */
  ogImage: "/og-image.png",
  ogImageWidth: 1200,
  ogImageHeight: 630,
  /** Twitter handle — left empty until the user provides one */
  twitterHandle: "",
} as const;

export const NAV_GROUPS: { label: string; items: { path: string; label: string }[] }[] = [
  {
    label: "Learn",
    items: [
      { path: "/learn", label: "All guides" },
      { path: "/learn/image-optimization-guide", label: "Image optimization" },
      { path: "/learn/jpeg-quality-guide", label: "JPEG quality settings" },
      { path: "/learn/compress-images-for-web", label: "Compress for web" },
      { path: "/learn/compress-images-without-uploading", label: "Compress without uploading" },
      { path: "/learn/webp-vs-avif", label: "WebP vs AVIF" },
      { path: "/learn/core-web-vitals-images", label: "Core Web Vitals" },
      { path: "/learn/best-free-image-compression-tools", label: "Best free tools" },
    ],
  },
  {
    label: "Formats",
    items: [
      { path: "/formats/webp", label: "WebP" },
      { path: "/formats/avif", label: "AVIF" },
      { path: "/formats/jpeg", label: "JPEG" },
      { path: "/formats/png", label: "PNG" },
    ],
  },
  {
    label: "Tools",
    items: [
      { path: "/tools/image-resizer", label: "Image resizer" },
      { path: "/tools/image-converter", label: "Image converter" },
    ],
  },
  {
    label: "Reference",
    items: [
      { path: "/glossary", label: "Glossary" },
      { path: "/about", label: "About" },
      { path: "/privacy", label: "Privacy" },
    ],
  },
];

/**
 * The Pro entry point, kept out of NAV_GROUPS on purpose.
 *
 * NAV_PATHS is used to build the footer's "every page" link block and the
 * llms.txt link list — both of which should describe the *content* of the site,
 * not its checkout. The Pro page is also noindex, so listing it as a site page
 * would contradict its robots tag. It gets its own prominent button in the
 * header instead.
 */
export const PRO_NAV_ITEM = { path: "/pro", label: "Pro" };

/** Flat list of every navigable + indexable path (drives the nav + footer). */
export const NAV_PATHS = NAV_GROUPS.flatMap((g) => g.items.map((i) => i.path));
